version: '2'
services:
    webapp:
        build: ./php-apache
        image: webapp
        container_name: pykniem-web
        hostname: pykniem-web
        ports:
            - "80:80"
        links:
            - mysql
        volumes:
            - /home/tszymanek/projects/pykniem:/var/www/html/webapp
        working_dir: /var/www/html/webapp
    mysql:
        image: mysql:5.7
        container_name: pykniem-db
        hostname: pykniem-db
        ports:
            - "3306:3306"
        volumes:
            - ./volumes/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: pykniem
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    # mongo:
    #     image: mongo:3.4
    #     container_name: shop-mongo
    #     hostname: mongo
    #     ports:
    #         - "27017:27017"
    #     volumes:
    #         - /home/tszymanek/mongo:/data/db
